### PR TITLE
Fixup support for Nix 2.23.0 and later

### LINKED ISSUE #120: Unrecognized flag error --commit-lockfile-summary
I was trying out the first given example
```bash
name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
```

Workflow fails with below error
```bash
Run DeterminateSystems/update-flake-lock@main
Run echo "GIT_AUTHOR_NAME=github-actions[bot]" >> $GITHUB_ENV
Run node "$GITHUB_ACTION_PATH/dist/index.js"
/nix/var/nix/profiles/default/bin/nix flake update --commit-lock-file --commit-lockfile-summary flake.lock: Update
error: unrecognised flag '--commit-lockfile-summary'
Try '/nix/var/nix/profiles/default/bin/nix --help' for more information.
Error: Error: The process '/nix/var/nix/profiles/default/bin/nix' failed with exit code 1
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by cole-h**
##### Description

Closes #120 

##### Checklist

- [x] Tested functionality against a test repository (see ["How to test changes"](../README.md#how-to-test-changes))
  * https://github.com/cole-h/update-flake-lock-test/actions/runs/9718244785/job/26825673600 and https://github.com/cole-h/update-flake-lock-test/pull/41
- [ ] Added or updated relevant documentation (leave unchecked if not applicable)

### CODE REVIEW

File: src/nix.ts [hunk 1]
```diff
@@ -9,10 +9,23 @@ export function makeNixCommandArgs(
...
+  // the setting `commit-lock-file-summary` (https://github.com/NixOS/nix/pull/10691), and Nix does
+  // not treat aliases the same as their "real" setting by requiring setting aliases to be
+  // configured via `--option <alias name> <option value>`
+  // (https://github.com/NixOS/nix/issues/10989).
+  // So, we go the long way so that we can support versions both before and after Nix 2.23.0.
+  const lockfileSummaryFlags = [
+    "--option",
+    "commit-lockfile-summary",
+    commitMessage,
+  ];
```
Comment (colemickens) [inline src/nix.ts:22]: If I understand correctly, this *could* be `--commit-lock-file-summary`. But this is probably "safer", and more backward compatible?

**Review by colemickens — APPROVED** [review]

File: src/nix.ts (hunk 1 above)
Comment (cole-h) [reply src/nix.ts:22]: It could only be `--commit-lock-file-summary` on versions of Nix >=2.23.0. We don't require a "MSNV", so I wouldn't feel comfortable making that change.
